### PR TITLE
Parse parameterized types in data binding layouts

### LINKED ISSUE #61: List of custom type not imported in generated binding
Repro [here](https://github.com/pswaminathan/bazel-kt-databinding-crash/pull/9). I see in `bazel-out/android-armeabi-v7a-fastbuild/bin/app/_javac/app_lib-kotlin/app_lib-kotlin-java_tmp/com/example/databinding/lib/databinding` (note the lack of imports):

```java
package com.example.databinding.lib.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.databinding.Bindable;
import androidx.databinding.ViewDataBinding;
import java.lang.Object;

public abstract class ActivityMainBinding extends ViewDataBinding {
  @Bindable
  protected int mItem;

  @Bindable
  protected Object mItemContext;

  @Bindable
  protected List<MyModel> mMyObjects;

  @Bindable
  protected int mPosition;

  @Bindable
  protected int mVisibility;

  protected ActivityMainBinding(Object _bindingComponent, View _root, int _localFieldCount) {
    super(_bindingComponent, _root, _localFieldCount);
  }

  @NonNull
  public static ActivityMainBinding bind(View view) {
    throw new RuntimeException("Stub!");
  }

  @NonNull
  public static ActivityMainBinding bind(View view, Object component) {
    throw new RuntimeException("Stub!");
  }

  @Nullable
  public int getItem() {
    throw new RuntimeException("Stub!");
  }

  @Nullable
  public Object getItemContext() {
    throw new RuntimeException("Stub!");
  }

  @Nullable
  public List<MyModel> getMyObjects() {
    throw new RuntimeException("Stub!");
  }

  @Nullable
  public int getPosition() {
    throw new RuntimeException("Stub!");
  }

  @Nullable
  public int getVisibility() {
    throw new RuntimeException("Stub!");
  }

  @NonNull
  public static ActivityMainBinding inflate(LayoutInflater inflater) {
    throw new RuntimeException("Stub!");
  }

  @NonNull
  public static ActivityMainBinding inflate(LayoutInflater inflater, ViewGroup root,
      boolean attachToRoot) {
    throw new RuntimeException("Stub!");
  }

  @NonNull
  public static ActivityMainBinding inflate(LayoutInflater inflater, ViewGroup root,
      boolean attachToRoot, Object component) {
    throw new RuntimeException("Stub!");
  }

  public abstract void setItem(int var1);

  public abstract void setItemContext(Object var1);

  public abstract void setMyObjects(List<MyModel> var1);

  public abstract void setPosition(int var1);

  public abstract void setVisibility(int var1);
}
```

### PR DESCRIPTION
**Pull request by pswaminathan**
Fixes #61

### CODE REVIEW

**Comment by pswaminathan** [comment]
@arunkumar9t2 or anyone else, any thoughts on this? Looks like mainline has changed quite a bit since submitting this, and I'd like to understand if this can be merged if I resolve the conflicts.

**Comment by arunkumar9t2** [comment]
Sorry could not look at this sooner, I will check and get back.

**Comment by arunkumar9t2** [comment]
Hey @pswaminathan  thanks for handling this case, I was reading into how databinding does the parsing and came across this implementation which seems to handle generics correctly https://cs.android.com/androidx/platform/frameworks/data-binding/+/mirror-goog-studio-master-dev:compilerCommon/src/main/kotlin/android/databinding/tool/ext/ext.kt;l=214?q=ParameterizedTypeName&ss=androidx%2Fplatform%2Fframeworks%2Fdata-binding:compilerCommon%2F 

Do you think we could do that here?

**Comment by pswaminathan** [comment]
@arunkumar9t2 implemented and rebased!

**Pull request merged**
